// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDkrTgZdkHxRSPGTqWTlafW0ZIY1baVC0',
    appId: '1:940963736683:web:e4b533d9f917404c6ad52e',
    messagingSenderId: '940963736683',
    projectId: 'my-fyp-project-e84ff',
    authDomain: 'my-fyp-project-e84ff.firebaseapp.com',
    storageBucket: 'my-fyp-project-e84ff.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKA5wFuAbGSTGF2CAAJlUzbaP0r4amfhE',
    appId: '1:940963736683:android:257b51bb36aff9d46ad52e',
    messagingSenderId: '940963736683',
    projectId: 'my-fyp-project-e84ff',
    storageBucket: 'my-fyp-project-e84ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARDS8z_Kvia_VO_oka20xHBfncDOPquFc',
    appId: '1:940963736683:ios:adc9d4aa1a6d5d0e6ad52e',
    messagingSenderId: '940963736683',
    projectId: 'my-fyp-project-e84ff',
    storageBucket: 'my-fyp-project-e84ff.firebasestorage.app',
    iosBundleId: 'com.example.speakingSkillsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARDS8z_Kvia_VO_oka20xHBfncDOPquFc',
    appId: '1:940963736683:ios:adc9d4aa1a6d5d0e6ad52e',
    messagingSenderId: '940963736683',
    projectId: 'my-fyp-project-e84ff',
    storageBucket: 'my-fyp-project-e84ff.firebasestorage.app',
    iosBundleId: 'com.example.speakingSkillsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDkrTgZdkHxRSPGTqWTlafW0ZIY1baVC0',
    appId: '1:940963736683:web:d9f480122f5b01496ad52e',
    messagingSenderId: '940963736683',
    projectId: 'my-fyp-project-e84ff',
    authDomain: 'my-fyp-project-e84ff.firebaseapp.com',
    storageBucket: 'my-fyp-project-e84ff.firebasestorage.app',
  );
}
